"""Concatenate the public iron-monk docs into a single LLM-ingestible file.

Run via ``make llms`` from the repo root. Writes ``docs/llms-full.txt``.

The page list mirrors the section order in ``docs/llms.txt`` so the two
artifacts stay in lockstep. Order matters: agents reading top-to-bottom expect
quickstart -> concepts -> catalog -> advanced -> integrations -> reference.

Internal maintenance tooling. Not shipped in the wheel. Consumers never run it.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "llms-full.txt"

# Public doc tree in canonical reading order. Anything not listed is excluded
# on purpose (e.g. the llms artifacts themselves, the home landing page).
PAGES: list[tuple[str, Path]] = [
    ("Quickstart",                          DOCS / "getting_started.md"),
    ("Concepts overview",                   DOCS / "concepts" / "index.md"),
    ("Pillar 1 - The @monk Decorator",      DOCS / "concepts" / "decorator.md"),
    ("Pillar 2 - Constraints",              DOCS / "concepts" / "constraints.md"),
    ("Pillar 3 - Validation",               DOCS / "concepts" / "validation.md"),
    ("Pillar 4 - Errors",                   DOCS / "concepts" / "errors.md"),
    ("Constraints catalog overview",        DOCS / "constraints" / "index.md"),
    ("Constraints / Composition",           DOCS / "constraints" / "composition.md"),
    ("Constraints / Nullability",           DOCS / "constraints" / "nullability.md"),
    ("Constraints / Strings",               DOCS / "constraints" / "strings.md"),
    ("Constraints / Format & Identity",     DOCS / "constraints" / "format.md"),
    ("Constraints / Numeric",               DOCS / "constraints" / "numeric.md"),
    ("Constraints / Equality & Choice",     DOCS / "constraints" / "choice.md"),
    ("Constraints / Collections",           DOCS / "constraints" / "collections.md"),
    ("Constraints / Datetime & Schedule",   DOCS / "constraints" / "datetime.md"),
    ("Constraints / Filesystem",            DOCS / "constraints" / "filesystem.md"),
    ("Constraints / File Uploads",          DOCS / "constraints" / "uploads.md"),
    ("Constraints / Geospatial",            DOCS / "constraints" / "geospatial.md"),
    ("Constraints / Custom Messages",       DOCS / "constraints" / "custom.md"),
    ("Advanced overview",                   DOCS / "advanced" / "index.md"),
    ("Advanced / Cross-Field Validation",   DOCS / "advanced" / "cross_field.md"),
    ("Advanced / Context-Aware Validation", DOCS / "advanced" / "context.md"),
    ("Advanced / Customization",            DOCS / "advanced" / "customization.md"),
    ("Advanced / Execution Models",         DOCS / "advanced" / "execution.md"),
    ("Advanced / Settings & Type Metadata", DOCS / "advanced" / "settings.md"),
    ("Integrations overview",               DOCS / "examples" / "index.md"),
    ("Integrations / Strawberry GraphQL",   DOCS / "examples" / "strawberry.md"),
    ("Integrations / Starlette",            DOCS / "examples" / "starlette.md"),
    ("Integrations / FastAPI",              DOCS / "examples" / "fastapi.md"),
    ("Integrations / SQLAlchemy",           DOCS / "examples" / "sqlalchemy.md"),
    ("Integrations / Tortoise ORM",         DOCS / "examples" / "tortoise_orm.md"),
    ("Integrations / tyro CLI",             DOCS / "examples" / "tyro.md"),
    ("Integrations / beartype",             DOCS / "examples" / "beartype.md"),
    ("Integrations / App Configuration",    DOCS / "examples" / "app_config.md"),
    ("Reference / API",                     DOCS / "api_reference.md"),
    ("Reference / Benchmarks",              DOCS / "benchmarks.md"),
]

_YAML_FRONT_MATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)


def _read(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return _YAML_FRONT_MATTER.sub("", text).rstrip() + "\n"


def main() -> None:
    parts: list[str] = [
        "# iron-monk - full docs (flat)\n",
        (
            "> Concatenated full documentation for iron-monk, "
            "in canonical reading order. Generated by support/build_llms.py - "
            "do not hand-edit. For a navigable index see llms.txt; for a "
            "token-trimmed digest see llms-ctx.txt.\n"
        ),
    ]
    for title, path in PAGES:
        if not path.exists():
            raise SystemExit(f"missing doc page: {path}")
        parts.append(f"\n\n---\n\n# {title}\n\n_Source: `{path.relative_to(ROOT)}`_\n\n")
        parts.append(_read(path))

    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes, {sum(1 for _ in OUT.open()):,} lines)")


if __name__ == "__main__":
    main()